ktor:
  deployment:
    port: 8080
  application:
    dependencies:
      - com.example.RepositoriesKt.provideDatabase
      - com.example.UserRepository
      - com.example.GreetingServiceImpl
      - com.example.PrintStreamProviderKt.stdout
    modules:
      - com.example.ApplicationKt.module
      - com.example.LoggingKt.logging
database:
  connectionUrl: postgres://localhost:3037/admin

connection:
  domain: api.example.com
  path: /v1
  protocol: https